### ISSUE TITLE
Comments should directly link to output artifacts

### ISSUE THREAD

**Issue by JasonGross** [coq-community/run-coq-bug-minimizer#33]
Now that [`actions/upload@v4` supports getting the artifact ID during the workflow](https://github.com/actions/upload-artifact#using-outputs), we should directly link to the artifacts with [something like](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact) `https://api.github.com/repos/coq-community/run-coq-bug-minimizer/actions/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}/zip` or `${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/actions/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}/zip`
cf
```
    - uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: my-artifact
        path: path/to/artifact/content/

    - name: Output artifact ID
      run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'
```
